#!/usr/bin/env node
/**
 * Writes config/rules.json: how each scanner rule detects (presence probes,
 * control probes, or both), read from the scanner package itself.
 *
 * The content engine uses this so a post can never describe a rule as doing
 * something it does not do. Run after every scanner release; the corpus-scan
 * workflow runs it automatically.
 *
 *   node scripts/sync-rules.mjs                  # latest published asiscan-cli
 *   SCANNER_DIST=../asiscan/dist node scripts/sync-rules.mjs   # local build
 */
import { execFileSync } from 'node:child_process';
import { mkdtempSync, writeFileSync, readFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
import { path, today } from './lib/config.mjs';

let dist = process.env.SCANNER_DIST && resolve(process.env.SCANNER_DIST);
if (!dist) {
  const dir = mkdtempSync(join(tmpdir(), 'asiscan-rules-'));
  execFileSync('npm', ['install', '--no-audit', '--no-fund', '--prefix', dir, 'asiscan-cli@latest'], { stdio: 'ignore' });
  dist = join(dir, 'node_modules', 'asiscan-cli', 'dist');
}
const pkg = JSON.parse(readFileSync(join(dist, '..', 'package.json'), 'utf8'));
const m = await import(pathToFileURL(join(dist, 'index.js')).href);

const DETECTS = {
  both: 'both: presence probes flag a dangerous construct directly, and a control probe flags the risky behaviour when no mitigation evidence exists anywhere in the project',
  presence: 'presence only: flags a dangerous construct directly; it does not look for mitigations',
  control: 'control only: fires when the risky behaviour is present and no evidence of the standard mitigation exists in the project',
};

const rules = [...m.ASI_RULES, ...m.LLM_RULES, ...m.EU_AI_ACT_RULES].map((r) => {
  const kinds = (r.probes || []).map((p) => p.kind);
  const p = kinds.filter((k) => k === 'presence').length;
  const c = kinds.filter((k) => k === 'control').length;
  return {
    id: r.id, title: r.title, severity: r.severity,
    presenceProbes: p, controlProbes: c,
    detects: DETECTS[p && c ? 'both' : p ? 'presence' : 'control'],
    // What a finding from this rule actually reports, one line per probe.
    flags: (r.probes || []).map((pr) => pr.message).filter(Boolean),
  };
});

writeFileSync(path('config', 'rules.json'), JSON.stringify({
  $comment: 'Generated by scripts/sync-rules.mjs from the scanner package. Do not edit by hand.',
  scannerVersion: pkg.version,
  generatedOn: today(),
  rules,
}, null, 2) + '\n');
console.error(`config/rules.json: ${rules.length} rules from asiscan-cli ${pkg.version}`);
